# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - reservation-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          echo "Installing production dependencies..."
          if [ -f "package-lock.json" ]; then
            echo "Using package-lock.json with npm ci"
            npm ci --only=production
          else
            echo "No package-lock.json found, using npm install"
            npm install --only=production
          fi
          echo "Dependencies installed successfully"

      - name: Verify critical packages
        run: |
          echo "Checking critical packages..."
          npm list @azure/identity --depth=0 || echo "@azure/identity not found"
          npm list @azure/cosmos --depth=0 || echo "@azure/cosmos not found"
          npm list redis --depth=0 || echo "redis not found"
          npm list express --depth=0 || echo "express not found"

      - name: Test basic application syntax
        run: |
          echo "Testing application syntax..."
          node -c server.js && echo "server.js syntax OK" || echo "server.js has syntax errors"

      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          # Create deployment directory
          mkdir -p deployment-package
          
          # Copy everything except what we don't need
          cp -r . deployment-package/
          
          # Clean up unnecessary files in deployment package
          cd deployment-package
          rm -rf .git .github .gitignore README.md || echo "Cleanup completed"
          rm -rf tests __tests__ || echo "Test directories removed"
          
          # Verify deployment package
          echo "Deployment package contents:"
          ls -la
          
          echo "Package.json contents:"
          cat package.json | head -20

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reservation-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DD3BAEFE191341B4B330D368F72DBF3B }}